<a href="https://colab.research.google.com/github/skylabin/linearalgebra/blob/main/DataType.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Data Types in Numpy
Data type Object (dtype) in NumPy Python
Difficulty Level : Medium
Last Updated : 29 Nov, 2018
Every ndarray has an associated data type (dtype) object. This data type object (dtype) informs us about the layout of the array. This means it gives us information about :

Type of the data (integer, float, Python object etc.)
Size of the data (number of bytes)
Byte order of the data (little-endian or big-endian)
If the data type is a sub-array, what is its shape and data type.
The values of an ndarray are stored in a buffer which can be thought of as a contiguous block of memory bytes. So how these bytes will be interpreted is given by the dtype object.  

Constructing a data type (dtype) object : Data type object is an instance of numpy.dtype class and it can be created using numpy.dtype.
Parameters:

obj: Object to be converted to a data type object.
align : bool, optional
Add padding to the fields to match what a C compiler would output for a similar C-struct.
copy : bool, optional
Make a new copy of the data-type object. If False, the result may just be a reference to a built-in data-type object.

# Python Program to create a data type object
import numpy as np
  
# np.int16 is converted into a data type object.
print(np.dtype(np.int16))

In [2]:
import numpy as np

In [3]:
ints = np.array(range(3))
chars = np.array(list('ABCDEFGHIJKLMNOP'))
strings = np.array(["ABCDEFGHIJKLMNOP"])
print(chars.tobytes())
print(strings.tobytes())
print(ints.dtype, chars.dtype, strings.dtype)
# Atleast the <U16 means the number of bytes used in the string.
# But for a list it just shows as <U1 

b'A\x00\x00\x00B\x00\x00\x00C\x00\x00\x00D\x00\x00\x00E\x00\x00\x00F\x00\x00\x00G\x00\x00\x00H\x00\x00\x00I\x00\x00\x00J\x00\x00\x00K\x00\x00\x00L\x00\x00\x00M\x00\x00\x00N\x00\x00\x00O\x00\x00\x00P\x00\x00\x00'
b'A\x00\x00\x00B\x00\x00\x00C\x00\x00\x00D\x00\x00\x00E\x00\x00\x00F\x00\x00\x00G\x00\x00\x00H\x00\x00\x00I\x00\x00\x00J\x00\x00\x00K\x00\x00\x00L\x00\x00\x00M\x00\x00\x00N\x00\x00\x00O\x00\x00\x00P\x00\x00\x00'
int64 <U1 <U16


In [4]:
big_end_buffer = bytearray([0,1,3,2])
big_end_buffer

bytearray(b'\x00\x01\x03\x02')

## Broadcasting
## https://numpy.org/doc/stable/user/basics.broadcasting.html

In [5]:
x = np.arange(4)
xx = x.reshape(4,1)
y = np.ones(5)
z = np.ones((3,4))


In [6]:
x.shape

(4,)

In [7]:
y.shape

(5,)

In [8]:
x + y

ValueError: ignored

In [9]:
xx.shape

(4, 1)

In [10]:
y.shape

(5,)

In [13]:
xx

array([[0],
       [1],
       [2],
       [3]])

In [14]:
print(xx +y)

[[1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


In [15]:
x

array([0, 1, 2, 3])

In [16]:
z

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
x + z


array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [20]:
a = np.array([0.0, 10.0, 20.0, 30.0])
b = np.array([1.0, 2.0, 3.0])
c = a[:, np.newaxis]
c

array([[ 0.],
       [10.],
       [20.],
       [30.]])

In [21]:
c + b

array([[ 1.,  2.,  3.],
       [11., 12., 13.],
       [21., 22., 23.],
       [31., 32., 33.]])

In [22]:
x = np.array([('Rex', 9, 81.0), ('Fido', 3, 27.0)],
           dtype=[('name', 'U10'), ('age', 'i4'), ('weight', 'f4')])
x

array([('Rex', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])

In [23]:
x[1]

('Fido', 3, 27.)

In [25]:
# Note it allocates a Unsigned 10 butes for the string
# <i4 says Little endian integer of 32 bits
# <f4 says Little endian Float 32 bits
x

array([('Rex', 9, 81.), ('Fido', 3, 27.)],
      dtype=[('name', '<U10'), ('age', '<i4'), ('weight', '<f4')])