<a href="https://colab.research.google.com/github/skylabin/linearalgebra/blob/main/Mike_Cohen_part2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [52]:
# Follow Mike Cohen Data Animations in Python for Prime Numbers
import numpy as np
import matplotlib.pyplot as plt
from sympy import isprime

In [ ]:
isprime(4)

False

In [53]:
# Here is a nice way to update distance variable within 0,1,2,3
d = np.arange(4)
(d+1)%4

array([1, 2, 3, 0])

In [54]:
# unlike the error shown by Cohen video, this now gives False for any np.array
isprime(np.arange(7))

False

In [55]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [56]:
# we will use list comprehension a wow! technique of Python
# first we list the prime numbers till 100 then change to 100000
n = 100000
ps = [i for i in range(n) if isprime(i)]


In [ ]:
# Just bring your mouse over the variable and it will list it and 
# show the number of elements in the list and a short summary of it 
# It will show 9592 items
# ps

In [57]:
# To compute distance between adjacent prime numbers we can compute
# dist = ps[i] - ps[i - 1]
# but for first element starts with index 0
print(ps[0])
print(ps[0 - 1])
# This will give dist between first element 2 and last element 99991
# So we index from 1

2
99991


In [58]:
# initialize direction variable to 0
direction = 0
# initialize the matrix
xy = np.zeros((len(ps),2))
for i in range(1, len(ps)):
  #print("Value of i: ", i)
  dist = ps[i] - ps[i-1]
  # print(dist)
  # update the xy coordinates
  # we need to move north first with the distance. 
  # Moving Nort means staying on y axis and not changing x axis
  # xy[i-1,0] is the old x cordinate - it stays as is
  # xy[i-1]+ dist is the y coordinate that we modify by dist
  if direction == 0:
    xy[i,:] = [xy[i-1,0], xy[i-1,1] + dist]
    #print(xy[i])
  elif direction == 1:
    xy[i,:] = [xy[i-1,0] + dist, xy[i-1,1]]
    #print(xy[i])
  elif direction == 2:
    xy[i,:] = [xy[i-1,0], xy[i-1,1] - dist]
    #print(xy[i])
  elif direction == 3:
    xy[i,:] = [xy[i-1,0] - dist, xy[i-1,1]]
    #print(xy[i])

  # update direction 0,1,2,3,0...
  direction = (direction +1) %4




In [59]:
np.mean(xy, axis=0)

array([267.32485405, 312.02304003])